server:
  port: 9100
spring:
  datasource:
    url: jdbc:mysql://localhost/udemy_users?useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
role: ROLE_STUDENT
appuser:
  udemyuser:
    username: instructor
    password: instructor
    authorities: ROLE_APP
message: Login successful!