creditcards:
  issuers:
    - name: American Express
      starts-with: 34, 37
      lengths: 15
    - name: Discover
      starts-with: 6011, 644, 645, 646, 647, 648, 649, 65
      lengths: 16, 19
    - name: MasterCard
      starts-with: 51, 52, 53, 54, 55
      lengths: 16
    - name: Visa
      starts-with: 4
      lengths: 13, 16, 19