server:
  port: 8100
education:
  academies:
    - name : everyone codes
      location : Vienna
    - name : everyone codes
      location : Lower Austria
    - name : everyone codes
      location : Graz
  events :
    - name : Laser Tag
      location : 9th District
      students :
        - name : Thomas
          language : English, German
        - name : Luna
          language : English, Italian
    - name : Virtual Reality Games
      location : Home
      students :
        - name : Alice
          language : English, French
        - name : Roberto
          language : English, Spanish